version: '2'

services:
  app:
    build: .
    links:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - 9092:9092
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  schema-registry:
    image: confluent/schema-registry:latest